model:
  backbone: 'dinov2_s'

training:
  finetune: 'blocks.11'
  learning_rate: 1e-4
  neg_mul: 5

dataloader:
  resize: (224, 224)
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

ctl:
  temperature: 0.02

